language: python
sudo: false
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install codecov
install:
  - python setup.py develop
  - pip install -U -r dev-requirements.txt
script: nosetests --with-coverage --cover-package=subsetter
after_success:
  - codecov
